### ISSUE TITLE
Is it possible to control the width of the column ? 

### ISSUE THREAD

**Issue by narlas01** [codedge-llc/scribe#13]
Hi there, 
  my question is about visibility of a column which has huge data. 

<img width="1652" alt="Screen Shot 2019-03-27 at 04 18 52" src="https://user-images.githubusercontent.com/13116582/55050227-81144480-5047-11e9-9611-7ec657db8f23.png">

I have few other columns like Solution which has huge data, so table looks bit clumsy with so many dotted lines ( if you biggest screen and drag the table then can be understandable).

So is it possible to control the width of column so that data comes in multi rows ? 

Thanks in advanced.

**Comment by hpopp** [comment]
You can't control the width of each column, but you can control the width of the table overall.

```elixir
Scribe.print(data, width: 80)
```

It allocates column width proportionally to the size of the largest cell in the column, truncating the excess.

**Comment by narlas01** [comment]
Thanks for your response @hpopp
