### ISSUE TITLE
This library should be disabled by default in config.

### ISSUE THREAD

**Issue by Voronchuk** [codedge-llc/scribe#9]
One of our deps `kadabra` was using `scribe` with a default configs.

We never planned to use this library but it silently messed all our console output until we found the reason of it after a long research.

Please, disabled it by default in `dev.exs` and `test.exs`, as it produce unpredicted side-effects then used as sub dependency.

**Comment by Voronchuk** [comment]
Example of "mess":
<img width="1072" alt="screen shot 2018-03-16 at 17 53 38" src="https://user-images.githubusercontent.com/414573/37530765-0276acac-2943-11e8-9db4-547bd468a40e.png">

**Comment by hpopp** [comment]
Update kadabra, scribe was removed in `0.3.8`. 

It was marked as an optional dependency in earlier versions. I'm not exactly sure why you have it installed.

**Comment by Voronchuk** [comment]
Our dependency was using it like this:

```
defp deps do
    [{:joken, "~> 1.4"}, {:poison, "~> 2.2"}, {:kadabra, "~> 0.2.0"}, {:httpotion, "~> 3.0.2"}]
  end
```

It was installing `scribe` all the time, exact version of `kadabra` which we were using was `0.2.2`

**Comment by Voronchuk** [comment]
Generally my point is that this library brings unpredictable consequences if used as dependency in 3rd party library and it's extremely hard to track for unaware user who never installed it directly.

For our case we just disabled it in a local config:

```
config :scribe,
  compile_auto_inspect: false,
  auto_inspect: false
```

And recompiled it as dep after that: `mix deps.compile scribe`

**Comment by hpopp** [comment]
Make sure scribe has been updated to `0.8`, the auto-inspect overrides have been disabled by default. It was a required dependency in the `0.2.x` releases of kadabra, though I would highly recommend updating to `0.3.x`. There have been critical stability fixes since those releases.

**Comment by Voronchuk** [comment]
Thanks for the quick response, I'll close it but I suggest to leave it on repo in case someone will Google for similar issues.

**Comment by hpopp** [comment]
I guess you edited your comment. That config will not work for `0.6`/`0.7` versions of scribe. Lock the dependency at `~> 0.8`
